services:
  app:
    container_name: symfony_app
    image: php:8.2-fpm
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=prod

  web:
    container_name: nginx_symfony
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app