services:
  db:
    container_name: mysql_playground_db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "3640:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  pma:
    container_name: mysql_playground_pma
    image: phpmyadmin:latest
    restart: always
    environment:
      UPLOAD_LIMIT: 950M
    ports:
      - "8895:80"
    depends_on:
      - db

  app:
    container_name: symfony_app
    image: php:8.2-fpm
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=prod

  web:
    container_name: nginx_symfony
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx:ro
    depends_on:
      - app